default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: tsubu_development

test:
  <<: *default
  database: tsubu_test

production:
  <<: *default
  database: tsubu_production
  username: tsubu
  password: <%= ENV['TSUBU_DATABASE_PASSWORD'] %>
